---

  - name: /etc/default/grub - quick timeout
    replace:
      dest: /etc/default/grub
      regexp: '(GRUB_TIMEOUT)=.*'
      replace: '\1=0'

  - name: sysctl - disable ipv6
    sysctl:
      name: "{{item}}"
      value: 1
      state: present
    with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

  - name: ssh - listen ipv4
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^[# ]*(ListenAddress 0.0.0.0)'
      line: '\1'
      backrefs: yes
      state: present

  - name: ssh - disable ipv6
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^[# ]*ListenAddress ::'
      state: absent
